jwt:
  secret: 53cr3t
  expirationDateInMs: 0
  refreshExpirationDateInMs: 9000000

spring:
  data:
    rest:
      base-path: /api

  datasource:
    url: jdbc:postgresql://localhost:49158/ecommerce
    username: postgres
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: update
