spring:
  datasource:
    url: jdbc:mysql://localhost:3306/eccomerce?allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false&serverTimezone=Europe/Warsaw
    username: root
    password: Atu171195

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

    hibernate:
      ddl-auto: update

  data:
    rest:
      base-path: /api

  security:
    user:
      name: admin
      password: 53cr3t